import type { NextPage } from "next";
import Head from "next/head";

import Hero from "../components/Hero";
const Home: NextPage = () => {
  return (
    <main>
      <Head>
        <title>Setting up Next.js</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero
        heroHeading="Let's setup your Next.js!"
        heroDesc="Next.js with Tailwindcss and daisyUI makes your development fasteeer! Lorem ipsum dolor sit amet consectetur, adipisicing elit. Sint fugiat animi magni qui et hic esse, quae ipsa tempora dolorem?"
      />
    </main>
  );
};

export default Home;
