import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <main>
      <Head>
        <title>Setting up Next.js</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </main>
  );
};

export default Home;
